rules:
  - id: no-constant-condition
    pattern: |
      if ($X == true) {
        ...
      }
    message: "Avoid using constant conditions in if statements."
    languages: [java]
    severity: WARNING

  - id: no-hardcoded-credentials
    pattern: |
      $X = "password";
    message: "Avoid hardcoding credentials in your source code."
    languages: [java]
    severity: ERROR

  - id: no-system-exit
    pattern: |
      System.exit($X);
    message: "Avoid using System.exit() which can terminate the JVM abruptly."
    languages: [java]
    severity: WARNING
  - id: no-raw-types
    pattern: |
      List $X = $Y;
    message: "Avoid using raw types, use generic types instead"
    languages: [java]
    severity: WARNING

  - name: Post-deployment Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: .semgrep.yml
