rules:
  - id: no-constant-condition
    pattern: |
      if ($X == true) {
      }
    message: "Avoid using constant conditions in if statements."
    languages: [java]
    severity: WARNING

  - id: no-hardcoded-credentials
    pattern: |
      $X = "password";
    message: "Avoid hardcoding credentials in your source code."
    languages: [java]
    severity: ERROR
  - id: no-empty-catch
    patterns:
      - pattern: |
          catch ($E) {
          }
      - pattern: |
          catch ($E) {
            ;
          }
    message: "Empty catch block detected"
    languages: [java]
    severity: ERROR

  - id: no-system-exit
    pattern: |
      System.exit($ARG);
    message: "Avoid using System.exit()"
    languages: [java]
    severity: WARNING

  - id: no-raw-types
    pattern: |
      List $X = $Y;
    message: "Avoid using raw types, use generic types instead"
    languages: [java]
    severity: WARNING

  - id: avoid-printstacktrace
    pattern: |
      $EXCEPTION.printStackTrace();
    message: "Avoid using printStackTrace(), use a logger inst
