rules:
   - id: no-empty-catch
    pattern: |
      catch ($E) {
        ;
      }
    message: "Empty catch block detected"
    languages: [java]
    severity: ERROR
  - id: no-system-exit
    pattern: |
      System.exit($ARG);
    message: "Avoid using System.exit(). Consider using a different approach to terminate the program."
    languages: [java]
    severity: WARNING

  - id: no-raw-types
    pattern: |
      List $X = $Y;
    message: "Avoid using raw types. Use generic types instead (e.g., List<String> instead of List)."
    languages: [java]
    severity: WARNING

  - id: avoid-printstacktrace
    pattern: |
      $EXCEPTION.printStackTrace();
    message: "Avoid using printStackTrace(). Use a logger to log exceptions."
    languages: [java]
    severity: WARNING
