name: CI-CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: .semgrep.yml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-app-artifact
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: java-app-artifact
        path: ./target

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1

    - name: Upload to S3
      run: aws s3 sync target/ s3://my-java-app-bucket/

  post-deployment-scan:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Post-deployment Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: .semgrep.yml
