name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-app-artifact
        path: target/*.jar

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: .semgrep.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: java-app-artifact
        path: ./targe

 

